### ISSUE TITLE
Resuming to application if download crash

### ISSUE THREAD

**Issue by Akshaybil** [atzcx/AppVerUpdater#20]
If something went wrong during downloading process means App crashes. Is there any way to avoid it

**Comment by Akshaybil** [comment]
Logcat for above issue
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.ethics.sureshotgps_update, PID: 30755
                                                   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
                                                       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
                                                       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
                                                       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
                                                       at android.app.DialogFragment.dismissInternal(DialogFragment.java:292)
                                                       at android.app.DialogFragment.dismiss(DialogFragment.java:258)
                                                       at com.github.atzcx.appverupdater.AppVerUpdater$8.onFailure(AppVerUpdater.java:415)
                                                       at com.github.atzcx.appverupdater.HttpClient$AsyncDownloadRequest$1.onDownloadFailed(HttpClient.java:197)
                                                       at com.thin.downloadmanager.DownloadRequestQueue$CallBackDelivery$3.run(DownloadRequestQueue.java:72)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)


When I remove the below lines 
progressDialogFragment.dismiss();
                progressDialogFragment = null; 
from com.github.atzcx.appverupdater.AppVerUpdater$8.onFailure(AppVerUpdater.java:415)
means application is not crashing, but what is the best way to handle this?

**Comment by Akshaybil** [comment]
Logcat for above issue
12-01 17:16:47.336 30755-30755/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.ethics.sureshotgps_update, PID: 30755
                                                   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
                                                       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
                                                       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
                                                       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
                                                       at android.app.DialogFragment.dismissInternal(DialogFragment.java:292)
                                                       at android.app.DialogFragment.dismiss(DialogFragment.java:258)
                                                       at com.github.atzcx.appverupdater.AppVerUpdater$8.onFailure(AppVerUpdater.java:415)
                                                       at com.github.atzcx.appverupdater.HttpClient$AsyncDownloadRequest$1.onDownloadFailed(HttpClient.java:197)
                                                       at com.thin.downloadmanager.DownloadRequestQueue$CallBackDelivery$3.run(DownloadRequestQueue.java:72)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)

If I delete the below lines means
 progressDialogFragment.dismiss();
                progressDialogFragment = null; from com.github.atzcx.appverupdater.AppVerUpdater$8.onFailure(AppVerUpdater.java:415)
                                                      means crashing is occuring, but what is the best way to handle this?
